package receipt

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/shaunlmason/open-seed-engine/internal/gitx"
)

func TestMain(m *testing.M) {
	for _, kv := range [][2]string{
		{"GIT_AUTHOR_NAME", "test"}, {"GIT_AUTHOR_EMAIL", "test@test"},
		{"GIT_COMMITTER_NAME", "test"}, {"GIT_COMMITTER_EMAIL", "test@test"},
	} {
		os.Setenv(kv[0], kv[1])
	}
	os.Exit(m.Run())
}

const goodPlan = `# Plan

## Steps

1. Do the thing.

## File Scope

- src/

## Acceptance Criteria

- The thing is done.

## Validation Commands

- ` + "`true`" + `
`

type fixture struct {
	t    *testing.T
	dir  string
	repo *gitx.Repo
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	dir := t.TempDir()
	f := &fixture{t: t, dir: dir, repo: &gitx.Repo{Dir: dir}}
	f.git("init", "--initial-branch=main")
	return f
}

func (f *fixture) git(args ...string) string {
	f.t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = f.dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		f.t.Fatalf("git %v: %v: %s", args, err, out)
	}
	return strings.TrimSpace(string(out))
}

func (f *fixture) write(path, content string) {
	f.t.Helper()
	p := filepath.Join(f.dir, path)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		f.t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		f.t.Fatal(err)
	}
}

func (f *fixture) commitAll(msg string) {
	f.t.Helper()
	f.git("add", "-A")
	f.git("commit", "-q", "-m", msg)
}

// planOnMain commits a valid plan for id on main and creates branch seed/<id>.
func (f *fixture) planAndBranch(id string) {
	f.t.Helper()
	f.git("checkout", "-q", "main")
	f.write("plans/"+id+".md", goodPlan)
	f.commitAll("plan " + id)
	f.git("checkout", "-q", "-b", "seed/"+id)
}

func (f *fixture) generateAndCommitReceipt(id string) {
	f.t.Helper()
	r, err := Generate(f.repo, id, "main", Options{RunValidation: true, GeneratedBy: "ci"})
	if err != nil {
		f.t.Fatal(err)
	}
	if err := r.WriteFile(f.dir); err != nil {
		f.t.Fatal(err)
	}
	f.commitAll("receipt " + id)
}

func failuresContain(rep *Report, substr string) bool {
	for _, f := range rep.Failures {
		if strings.Contains(f, substr) {
			return true
		}
	}
	return false
}

// Passing fixture: plan merged, work done, receipt generated by "CI".
func TestVerifyHappyPath(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-1111")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-1111")

	rep, err := Verify(f.repo, "os-1111", "main", "seed/os-1111", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if !rep.OK {
		t.Fatalf("failures: %v", rep.Failures)
	}
}

// Done-when: plan tamper via task PR is rejected (purity).
func TestVerifyRejectsPlanTamperInTaskPR(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-2222")
	f.write("src/thing.txt", "done\n")
	// The attack: quietly weaken the plan inside the task PR.
	f.write("plans/os-2222.md", strings.Replace(goodPlan, "`true`", "`echo pwned`", 1))
	f.commitAll("implement + tamper")
	f.generateAndCommitReceipt("os-2222")

	rep, err := Verify(f.repo, "os-2222", "main", "seed/os-2222", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "may not touch plans/**") {
		t.Fatalf("tamper not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}
	// And the commands executed came from the merge-base blob, not the
	// tampered head copy.
	if rep.Regenerated.Validation[0].Cmd != "true" {
		t.Fatalf("validation ran head's plan: %v", rep.Regenerated.Validation)
	}
}

// Done-when: stale plan replay is rejected; rebasing (amendment flow)
// recovers, salvaging the work.
func TestVerifyStalePlanThenAmendmentFlow(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-3333")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-3333")

	// Plan amended on main after the branch based itself (the revocation).
	f.git("checkout", "-q", "main")
	f.write("plans/os-3333.md", strings.Replace(goodPlan, "Do the thing.", "Do the AMENDED thing.", 1))
	f.commitAll("amend plan os-3333")
	f.git("checkout", "-q", "seed/os-3333")

	rep, err := Verify(f.repo, "os-3333", "main", "seed/os-3333", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "plan changed since branch base") {
		t.Fatalf("stale plan not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}

	// Amendment flow: bring the base in (merge-base updates), regenerate the
	// receipt against the amended plan — prior work is salvaged, not reset.
	f.git("merge", "-q", "--no-edit", "main")
	f.generateAndCommitReceipt("os-3333")
	rep, err = Verify(f.repo, "os-3333", "main", "seed/os-3333", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if !rep.OK {
		t.Fatalf("post-rebase verify failed: %v", rep.Failures)
	}
	if content, _ := os.ReadFile(filepath.Join(f.dir, "src/thing.txt")); string(content) != "done\n" {
		t.Fatal("work was not salvaged")
	}
}

// Done-when: a forged local receipt is caught; the regenerated receipt is
// authoritative and overwrites it.
func TestVerifyForgedReceiptOverwritten(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-4444")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-4444")

	// Forge: claim a different diff hash (e.g. hiding an extra change).
	p := Path(f.dir, "os-4444")
	b, _ := os.ReadFile(p)
	forged := strings.Replace(string(b), `"diff_sha256": "`, `"diff_sha256": "0000`, 1)
	os.WriteFile(p, []byte(forged), 0o644)
	f.commitAll("forge receipt")

	rep, err := Verify(f.repo, "os-4444", "main", "seed/os-4444", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "receipt mismatch") {
		t.Fatalf("forgery not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}

	// Author of record: write the regenerated receipt over the forged one.
	if err := rep.Regenerated.WriteFile(f.dir); err != nil {
		t.Fatal(err)
	}
	f.commitAll("authoritative receipt")
	rep, err = Verify(f.repo, "os-4444", "main", "seed/os-4444", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if !rep.OK {
		t.Fatalf("post-overwrite verify failed: %v", rep.Failures)
	}
}

// No approved plan at the merge-base → generation refuses (D3: no plan, no
// implementation above L1).
func TestGenerateRequiresMergeBasePlan(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.git("checkout", "-q", "-b", "seed/os-5555")
	f.write("src/thing.txt", "rogue\n")
	f.commitAll("rogue work")
	if _, err := Generate(f.repo, "os-5555", "main", Options{}); err == nil ||
		!strings.Contains(err.Error(), "no approved plan at merge-base") {
		t.Fatalf("err = %v", err)
	}
}

// A failing validation command fails verify.
func TestVerifyFailsOnRedValidation(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.git("checkout", "-q", "main")
	f.write("plans/os-6666.md", strings.Replace(goodPlan, "`true`", "`false`", 1))
	f.commitAll("plan os-6666")
	f.git("checkout", "-q", "-b", "seed/os-6666")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	r, err := Generate(f.repo, "os-6666", "main", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	r.WriteFile(f.dir)
	f.commitAll("receipt")

	rep, err := Verify(f.repo, "os-6666", "main", "seed/os-6666", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "validation command failed") {
		t.Fatalf("red validation not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}
}

// Verify refuses to run against a non-task branch (merge-queue guidance).
func TestVerifyRefusesNonTaskBranch(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	if _, err := Verify(f.repo, "os-7777", "main", "gh-readonly-queue/main/pr-9", Options{}); err == nil {
		t.Fatal("merge-group ref accepted as task branch")
	}
}
