package receipt

import (
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/shaunlmason/open-seed-engine/internal/gitx"
)

func TestMain(m *testing.M) {
	for _, kv := range [][2]string{
		{"GIT_AUTHOR_NAME", "test"}, {"GIT_AUTHOR_EMAIL", "test@test"},
		{"GIT_COMMITTER_NAME", "test"}, {"GIT_COMMITTER_EMAIL", "test@test"},
	} {
		os.Setenv(kv[0], kv[1])
	}
	os.Exit(m.Run())
}

const goodPlan = `# Plan

## Steps

1. Do the thing.

## File Scope

- src/

## Acceptance Criteria

- The thing is done.

## Validation Commands

- ` + "`true`" + `
`

type fixture struct {
	t    *testing.T
	dir  string
	repo *gitx.Repo
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	dir := t.TempDir()
	f := &fixture{t: t, dir: dir, repo: &gitx.Repo{Dir: dir}}
	f.git("init", "--initial-branch=main")
	return f
}

func (f *fixture) git(args ...string) string {
	f.t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = f.dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		f.t.Fatalf("git %v: %v: %s", args, err, out)
	}
	return strings.TrimSpace(string(out))
}

func (f *fixture) write(path, content string) {
	f.t.Helper()
	p := filepath.Join(f.dir, path)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		f.t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		f.t.Fatal(err)
	}
}

func (f *fixture) commitAll(msg string) {
	f.t.Helper()
	f.git("add", "-A")
	f.git("commit", "-q", "-m", msg)
}

// planOnMain commits a valid plan for id on main and creates branch seed/<id>.
func (f *fixture) planAndBranch(id string) {
	f.t.Helper()
	f.git("checkout", "-q", "main")
	f.write("plans/"+id+".md", goodPlan)
	f.commitAll("plan " + id)
	f.git("checkout", "-q", "-b", "seed/"+id)
}

func (f *fixture) generateAndCommitReceipt(id string) {
	f.t.Helper()
	r, err := Generate(f.repo, id, "main", Options{RunValidation: true, GeneratedBy: "ci"})
	if err != nil {
		f.t.Fatal(err)
	}
	if err := r.WriteClaim(f.dir); err != nil {
		f.t.Fatal(err)
	}
	f.commitAll("receipt " + id)
}

func (f *fixture) verify(id string) *Report {
	f.t.Helper()
	rep, err := Verify(f.repo, id, "main", "seed/"+id, Options{RunValidation: true})
	if err != nil {
		f.t.Fatal(err)
	}
	return rep
}

func failuresContain(rep *Report, substr string) bool {
	for _, f := range rep.Failures {
		if strings.Contains(f, substr) {
			return true
		}
	}
	return false
}

// Passing fixture: plan merged, work done, receipt generated by "CI".
func TestVerifyHappyPath(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-1111")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-1111")

	rep, err := Verify(f.repo, "os-1111", "main", "seed/os-1111", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if !rep.OK {
		t.Fatalf("failures: %v", rep.Failures)
	}
}

// Done-when: plan tamper via task PR is rejected (purity).
func TestVerifyRejectsPlanTamperInTaskPR(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-2222")
	f.write("src/thing.txt", "done\n")
	// The attack: quietly weaken the plan inside the task PR.
	f.write("plans/os-2222.md", strings.Replace(goodPlan, "`true`", "`echo pwned`", 1))
	f.commitAll("implement + tamper")
	f.generateAndCommitReceipt("os-2222")

	rep, err := Verify(f.repo, "os-2222", "main", "seed/os-2222", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "may not touch plans/**") {
		t.Fatalf("tamper not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}
	// And the commands executed came from the merge-base blob, not the
	// tampered head copy.
	if rep.Regenerated.Validation[0].Cmd != "true" {
		t.Fatalf("validation ran head's plan: %v", rep.Regenerated.Validation)
	}
}

// Done-when: stale plan replay is rejected; rebasing (amendment flow)
// recovers, salvaging the work.
func TestVerifyStalePlanThenAmendmentFlow(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-3333")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-3333")

	// Plan amended on main after the branch based itself (the revocation).
	f.git("checkout", "-q", "main")
	f.write("plans/os-3333.md", strings.Replace(goodPlan, "Do the thing.", "Do the AMENDED thing.", 1))
	f.commitAll("amend plan os-3333")
	f.git("checkout", "-q", "seed/os-3333")

	rep, err := Verify(f.repo, "os-3333", "main", "seed/os-3333", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "plan changed since branch base") {
		t.Fatalf("stale plan not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}

	// Amendment flow: bring the base in (merge-base updates), regenerate the
	// receipt against the amended plan: prior work is salvaged, not reset.
	f.git("merge", "-q", "--no-edit", "main")
	f.generateAndCommitReceipt("os-3333")
	rep, err = Verify(f.repo, "os-3333", "main", "seed/os-3333", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if !rep.OK {
		t.Fatalf("post-rebase verify failed: %v", rep.Failures)
	}
	if content, _ := os.ReadFile(filepath.Join(f.dir, "src/thing.txt")); string(content) != "done\n" {
		t.Fatal("work was not salvaged")
	}
}

// Done-when: a forged local receipt is caught. What a claim can lie about is
// which plan it was implemented against, and that is what is compared: the
// regenerated claim is authoritative and overwrites it (R11).
func TestVerifyForgedPlanPinOverwritten(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-4444")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-4444")

	// Forge: claim a plan pin that is not the approved plan's, the way an
	// implementer would to make work against an unapproved plan look gated.
	p := Path(f.dir, "os-4444")
	b, _ := os.ReadFile(p)
	forged := strings.Replace(string(b), `"plan_sha256": "`, `"plan_sha256": "0000`, 1)
	os.WriteFile(p, []byte(forged), 0o644)
	f.commitAll("forge receipt")

	rep := f.verify("os-4444")
	if rep.OK || !failuresContain(rep, "but the approved plan at the merge base is") {
		t.Fatalf("forgery not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}

	// Author of record: write the regenerated claim over the forged one.
	if err := rep.Regenerated.WriteClaim(f.dir); err != nil {
		t.Fatal(err)
	}
	f.commitAll("authoritative receipt")
	if rep := f.verify("os-4444"); !rep.OK {
		t.Fatalf("post-overwrite verify failed: %v", rep.Failures)
	}
}

// The claim is stable under everything that used to invalidate it. A receipt
// generated mid-branch survives further commits, a merge of the base, and the
// base moving underneath: none of those change the plan it was implemented
// against, and the snapshot they do change is CI's to recompute (R11). This is
// the regression that made the gate a bottleneck: every one of these pushes
// used to turn verify red with "receipt mismatch".
func TestClaimSurvivesLaterPushesAndBaseMerges(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-8888")
	f.write("src/thing.txt", "first\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-8888")
	if rep := f.verify("os-8888"); !rep.OK {
		t.Fatalf("baseline verify failed: %v", rep.Failures)
	}

	// A review fix lands after the receipt.
	f.write("src/thing.txt", "reviewed\n")
	f.commitAll("address review")
	if rep := f.verify("os-8888"); !rep.OK {
		t.Fatalf("a later content commit invalidated the claim: %v", rep.Failures)
	}

	// Unrelated work lands on the base and the branch takes it, moving the
	// merge base and with it the whole diff.
	f.git("checkout", "-q", "main")
	f.write("other/file.txt", "unrelated\n")
	f.commitAll("unrelated work on main")
	f.git("checkout", "-q", "seed/os-8888")
	f.git("merge", "-q", "--no-edit", "main")
	if rep := f.verify("os-8888"); !rep.OK {
		t.Fatalf("merging the base invalidated the claim: %v", rep.Failures)
	}
}

// A branch cut before its own plan PR merged is a mechanical problem with one
// remedy, not a D3 violation, and says so.
func TestPlanMergedAfterTheBranchWasCut(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.git("checkout", "-q", "-b", "seed/os-9999")
	f.write("src/thing.txt", "work\n")
	f.commitAll("implement")
	// The plan PR merges only now, after the branch point.
	f.git("checkout", "-q", "main")
	f.write("plans/os-9999.md", goodPlan)
	f.commitAll("plan os-9999")
	f.git("checkout", "-q", "seed/os-9999")

	rep := f.verify("os-9999")
	if rep.OK || !failuresContain(rep, "merged after this branch was cut") {
		t.Fatalf("diagnosis missing: ok=%v failures=%v", rep.OK, rep.Failures)
	}
	if failuresContain(rep, "no approved plan") {
		t.Fatal("a branch behind its plan was reported as an unplanned branch")
	}
	// The remedy the message names actually works.
	f.git("merge", "-q", "--no-edit", "main")
	f.generateAndCommitReceipt("os-9999")
	if rep := f.verify("os-9999"); !rep.OK {
		t.Fatalf("the named remedy did not clear the gate: %v", rep.Failures)
	}
}

// A task PR may touch no receipt but its own. The hashed diff excludes
// receipts/**, so purity has to run over the full changed-file list or this
// laundering path is invisible to every gate.
func TestVerifyRejectsForeignReceiptInTaskPR(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-aaaa")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-aaaa")
	f.write("receipts/os-victim.json", `{"schema_version":"2.0","task":"os-victim"}`+"\n")
	f.commitAll("smuggle another task's receipt")

	rep := f.verify("os-aaaa")
	if rep.OK || !failuresContain(rep, "may touch no receipt but its own") {
		t.Fatalf("foreign receipt not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}
}

// Schema 1.0 receipts predate the split and stay readable: their durable
// fields are a subset, and migrate rewrites them in place.
func TestReadsSchema1AndMigrates(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-bbbb")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")

	r, err := Generate(f.repo, "os-bbbb", "main", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	// The 1.0 shape: the snapshot inline, the commands only as results.
	legacy := map[string]any{
		"schema_version": "1.0",
		"task":           "os-bbbb",
		"merge_base":     r.MergeBase,
		"head":           r.Head,
		"plan_path":      r.PlanPath,
		"plan_sha256":    r.PlanSHA256,
		"diff_files":     r.DiffFiles,
		"diff_sha256":    r.DiffSHA256,
		"validation":     []map[string]any{{"cmd": "true", "exit": 0}},
		"generated_by":   "local",
	}
	b, _ := json.MarshalIndent(legacy, "", "  ")
	f.write("receipts/os-bbbb.json", string(b)+"\n")
	f.commitAll("legacy receipt")

	if rep := f.verify("os-bbbb"); !rep.OK {
		t.Fatalf("a 1.0 receipt was rejected: %v", rep.Failures)
	}

	p := Path(f.dir, "os-bbbb")
	changed, err := Migrate(p)
	if err != nil || !changed {
		t.Fatalf("migrate: changed=%v err=%v", changed, err)
	}
	c, err := ReadClaim(p)
	if err != nil {
		t.Fatal(err)
	}
	if c.SchemaVersion != SchemaVersion || !slices.Equal(c.ValidationCommands, []string{"true"}) {
		t.Fatalf("migrated claim = %+v", c)
	}
	if raw, _ := os.ReadFile(p); strings.Contains(string(raw), "diff_sha256") {
		t.Fatal("the migrated file still carries the snapshot")
	}
	if again, err := Migrate(p); err != nil || again {
		t.Fatalf("migrate is not idempotent: changed=%v err=%v", again, err)
	}
}

// The attestation is what CI emits per run: the claim plus the snapshot it
// verified against, written whether the gate passed or not.
func TestAttestationCarriesTheVerifiedSnapshot(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.planAndBranch("os-cccc")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	f.generateAndCommitReceipt("os-cccc")

	rep, err := Verify(f.repo, "os-cccc", "main", "seed/os-cccc", Options{RunValidation: true, VerifiedBy: "ci:run/1"})
	if err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(t.TempDir(), "attestation.json")
	if err := rep.Regenerated.WriteAttestation(out); err != nil {
		t.Fatal(err)
	}
	var got Receipt
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(b, &got); err != nil {
		t.Fatal(err)
	}
	if got.MergeBase == "" || got.DiffSHA256 == "" || got.VerifiedBy != "ci:run/1" {
		t.Fatalf("attestation = %+v", got)
	}
	if !slices.Equal(got.DiffFiles, []string{"src/thing.txt"}) {
		t.Fatalf("diff files = %v", got.DiffFiles)
	}
	// The committed claim carries none of it.
	if raw, _ := os.ReadFile(Path(f.dir, "os-cccc")); strings.Contains(string(raw), "merge_base") {
		t.Fatal("the committed claim carries the snapshot")
	}
}

// No approved plan at the merge-base → generation refuses (D3: no plan, no
// implementation above L1).
func TestGenerateRequiresMergeBasePlan(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.git("checkout", "-q", "-b", "seed/os-5555")
	f.write("src/thing.txt", "rogue\n")
	f.commitAll("rogue work")
	_, err := Generate(f.repo, "os-5555", "main", Options{})
	var pe *PlanError
	if !errors.As(err, &pe) || !strings.Contains(err.Error(), "no approved plan") {
		t.Fatalf("err = %v", err)
	}
}

// A failing validation command fails verify.
func TestVerifyFailsOnRedValidation(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	f.git("checkout", "-q", "main")
	f.write("plans/os-6666.md", strings.Replace(goodPlan, "`true`", "`false`", 1))
	f.commitAll("plan os-6666")
	f.git("checkout", "-q", "-b", "seed/os-6666")
	f.write("src/thing.txt", "done\n")
	f.commitAll("implement")
	r, err := Generate(f.repo, "os-6666", "main", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if err := r.WriteClaim(f.dir); err != nil {
		t.Fatal(err)
	}
	f.commitAll("receipt")

	rep, err := Verify(f.repo, "os-6666", "main", "seed/os-6666", Options{RunValidation: true})
	if err != nil {
		t.Fatal(err)
	}
	if rep.OK || !failuresContain(rep, "validation command failed") {
		t.Fatalf("red validation not caught: ok=%v failures=%v", rep.OK, rep.Failures)
	}
}

// Verify refuses to run against a non-task branch (merge-queue guidance).
func TestVerifyRefusesNonTaskBranch(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hi\n")
	f.commitAll("init")
	if _, err := Verify(f.repo, "os-7777", "main", "gh-readonly-queue/main/pr-9", Options{}); err == nil {
		t.Fatal("merge-group ref accepted as task branch")
	}
}

func TestClaimComparisonAndWriteClaim(t *testing.T) {
	want := Claim{Task: "os-t", PlanPath: "plans/os-t.md", PlanSHA256: "abc", ValidationCommands: []string{"x", "y"}}
	if d := want.Differs(want); d != "" {
		t.Fatalf("a claim differs from itself: %s", d)
	}
	for _, tc := range []struct {
		name string
		got  Claim
		want string
	}{
		{"task", Claim{Task: "os-other"}, "not \"os-t\""},
		{"plan path", Claim{Task: "os-t", PlanPath: "plans/other.md"}, "plan path"},
		{"plan pin", Claim{Task: "os-t", PlanPath: "plans/os-t.md", PlanSHA256: "def"}, "plan pin"},
		{"commands", Claim{Task: "os-t", PlanPath: "plans/os-t.md", PlanSHA256: "abc", ValidationCommands: []string{"x"}}, "validation commands"},
	} {
		if d := tc.got.Differs(want); !strings.Contains(d, tc.want) {
			t.Fatalf("%s: %q does not mention %q", tc.name, d, tc.want)
		}
	}

	r := &Receipt{Claim: Claim{SchemaVersion: SchemaVersion, Task: "os-t"}, DiffSHA256: "deadbeef"}
	root := t.TempDir()
	if err := r.WriteClaim(root); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(Path(root, "os-t"))
	if err != nil {
		t.Fatal("receipt not written")
	}
	if strings.Contains(string(b), "deadbeef") {
		t.Fatal("WriteClaim wrote the snapshot")
	}
}

// The diff hash is a claim about the change, not about the clone that
// computed it: git abbreviates the index line's blob ids to a length
// that grows with the object count (seven hex digits below 16384
// objects, eight above), so without --full-index a receipt generated
// in a partial clone mismatched in CI's full clone once the repository
// crossed that count. Two clones that differ only in core.abbrev, the
// knob that stands in for the object count, hash the same diff.
func TestDiffHashIsIndependentOfTheCloneAbbreviation(t *testing.T) {
	f := newFixture(t)
	f.write("README.md", "hello\n")
	f.commitAll("init")
	f.planAndBranch("os-abbrev")
	f.write("src/a.go", "package a\n")
	f.commitAll("work")

	f.git("config", "core.abbrev", "7")
	short, err := Generate(f.repo, "os-abbrev", "main", Options{})
	if err != nil {
		t.Fatal(err)
	}
	f.git("config", "core.abbrev", "40")
	long, err := Generate(f.repo, "os-abbrev", "main", Options{})
	if err != nil {
		t.Fatal(err)
	}
	if short.DiffSHA256 != long.DiffSHA256 {
		t.Fatalf("the diff hash depends on core.abbrev: %s vs %s", short.DiffSHA256, long.DiffSHA256)
	}
	// The bytes hashed carry the full ids, so no abbreviation can reach them.
	out, err := f.repo.Git("diff", "--full-index", short.MergeBase, short.Head, "--", ".", diffExclude)
	if err != nil {
		t.Fatal(err)
	}
	if !regexp.MustCompile(`(?m)^index [0-9a-f]{40}\.\.[0-9a-f]{40}`).MatchString(out) {
		t.Fatalf("the hashed diff does not carry full blob ids:\n%s", out)
	}
}
